[package]
name = "Reframe"
version = "2.7.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] }
anyhow = "1.0"
async-trait = "0.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"  # For detailed JSON deserialization error paths
quick-xml = { version = "0.37", features = ["serialize"] }  # For XML serialization

dataflow-rs = "0.1.28"
# dataflow-rs = { path = "../dataflow-rs" }
swift-mt-message = { version = "2.3.7" }
# swift-mt-message = { path = "../SwiftMTMessage/swift-mt-message" }
mx-message = "0.1.9"

# Tracing and logging dependencies
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-log = "0.2"
tracing-appender = "0.2"
regex = "1.0"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
serde-xml-rs = "0.8.1"
