[package]
name = "Reframe"
version = "1.5.4"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] }
anyhow = "1.0"
async-trait = "0.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"  # For detailed JSON deserialization error paths
quick-xml = { version = "0.31", features = ["serialize"] }  # For XML serialization

dataflow-rs = "0.1.20"
swift-mt-message = { version = "2.2.5" }
# swift-mt-message = { path = "../SwiftMTMessage/swift-mt-message" }
mx-message = "0.1.8"
